### ISSUE TITLE
PR not listed

### ISSUE THREAD

**Issue by ericLemanissier** [prince-chrismc/conan-center-index-pending-review#7]
this PR is not listed, whereas it was pushed less than 24h ago: https://github.com/conan-io/conan-center-index/pull/4182
Is this expected ?

**Comment by prince-chrismc** [comment]
Yes I had added a review and it was removed from the table

**Comment by ericLemanissier** [comment]
Ok, I thought that "No reviews" meant "No reviews since the last push", but it means "no reviews on any version of the PR" right ?
In this case Wouldn't it be pertinent to consider only reviews which happened after the last push ?

**Comment by prince-chrismc** [comment]
> Ok, I thought that "No reviews" meant "No reviews since the last push", but it means "no reviews on any version of the PR" right ?

Spot on

> Wouldn't it be pertinent to consider only reviews which happened after the last push ?

I do so for the approvals/blockers....

My logic was that an approval is the indication of the PR being completed/ironed out, ie someone had already taken the time to review it... no longer rough draft.

Being more flexible might drastically increase the quantity needing review... which would be accurate reflection... 
depends how many PRs we want in this list... 
My original goal was to have a list of "easy reviews" since the hard part was already done.

It might be worth formalizing a definition of the "review process"

**Comment by prince-chrismc** [comment]
certainly an area for improvement
